import Foundation
import SwiftData

/// SwiftData model for one Diak-owned chat session.
///
/// Per Decision #13/#14 of `Docs/PROJECT_STATE.md`, Diak owns its own
/// sessions, messages, and runs — the dashboard's `/api/sessions`
/// surface is **read-only** historical data from Hermes itself.
/// `DiakSession` is the Swift-side row backing Diak's chat composer
/// and Phase 3 chat history UI.
///
/// Field choices:
/// - `id`: stable identity, set at creation time. UUID v4 generated by
///   `UUID()`. The store uses `id` for primary-key lookups via
///   `#Predicate { $0.id == … }`.
/// - `title`: short human-readable label. Defaults to a stub derived
///   from the first prompt; the chat composer view will let the user
///   rename it.
/// - `createdAt` / `updatedAt`: ISO timestamps. `updatedAt` is bumped
///   on any mutation (`addMessage`, `setTitle`, etc.).
/// - `model` / `providerId` / `profileName`: capture the inference
///   shape the API Server used so a later "what model produced this?"
///   inspection works without consulting Hermes' own session table.
/// - `systemPrompt`: optional. Phase 3 may inject one; Phase 1 stores
///   whatever the caller passes (typically nil).
@available(macOS 14.0, *)
@Model
public final class DiakSession {
    @Attribute(.unique) public var id: UUID
    public var title: String
    public var createdAt: Date
    public var updatedAt: Date
    public var model: String?
    public var systemPrompt: String?
    public var profileName: String?
    public var providerId: String?

    @Relationship(deleteRule: .cascade, inverse: \DiakMessage.session)
    public var messages: [DiakMessage] = []

    @Relationship(deleteRule: .cascade, inverse: \DiakRun.session)
    public var runs: [DiakRun] = []

    public init(
        id: UUID = UUID(),
        title: String,
        createdAt: Date = Date(),
        updatedAt: Date? = nil,
        model: String? = nil,
        systemPrompt: String? = nil,
        profileName: String? = nil,
        providerId: String? = nil
    ) {
        self.id = id
        self.title = title
        self.createdAt = createdAt
        self.updatedAt = updatedAt ?? createdAt
        self.model = model
        self.systemPrompt = systemPrompt
        self.profileName = profileName
        self.providerId = providerId
    }
}
