#!/usr/bin/env python3
"""Production Diak ↔ Hermes Agent bridge.

This is intentionally separate from ``diak_dev_daemon.py``.  The dev daemon is a
fixture server for UI dogfood; this bridge invokes the real Hermes Agent runtime
resolved from the user's Hermes gateway configuration and exposes the typed HTTP
contract consumed by Diak.
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import os
import queue
import re
import subprocess
import sys
import tempfile
import threading
import time
import traceback
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any, Callable, Iterable
from urllib.parse import urlencode, urlparse

BRIDGE_VERSION = "diak-hermes-bridge-1.0.0"
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8765
DEFAULT_STATE_PATH = Path.home() / ".hermes" / "diak" / "bridge_state.json"
MAX_BODY_BYTES = 2_000_000


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def json_dumps(payload: Any) -> str:
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":"))


def make_id(prefix: str) -> str:
    return f"{prefix}-{uuid.uuid4().hex[:16]}"


def title_from_prompt(prompt: str) -> str:
    squashed = re.sub(r"\s+", " ", prompt).strip()
    if not squashed:
        return "New Hermes session"
    return squashed[:80]


def _strip_markdown_fence(text: str) -> str:
    match = re.search(r"```(?:html|HTML)?\s*(.*?)```", text, flags=re.DOTALL)
    return match.group(1).strip() if match else text.strip()


def artifact_from_response(session_id: str, prompt: str, response: str) -> dict[str, Any] | None:
    """Best-effort typed canvas artifact extraction for real Hermes responses.

    The production bridge does not execute browser/code tools itself. When the
    real Hermes runtime returns website/canvas-shaped content, preserve it as a
    typed Diak artifact so the Mac app can render the result in Canvas instead
    of leaving the response trapped in chat text.
    """
    haystack = f"{prompt}\n{response}".lower()
    if not any(token in haystack for token in ("canvas", "website", "html", "landing page", "marketing site")):
        return None
    body = _strip_markdown_fence(response)
    kind = "browser" if ("<html" in body.lower() or "<!doctype" in body.lower() or "website" in haystack) else "document"
    title = "Generated website" if kind == "browser" else title_from_prompt(prompt)
    return {
        "id": make_id("canvas-art"),
        "session_id": session_id,
        "kind": kind,
        "title": title,
        "summary": "Generated by the real Hermes Agent runtime through the production bridge.",
        "preview": body[:20000],
        "created_at": utc_now(),
        "ref": {"id": make_id("generated"), "kind": "generated", "title": title, "detail": "production_bridge"},
    }


@dataclass(frozen=True)
class RuntimeResult:
    text: str
    hermes_session_id: str | None = None
    model: str | None = None
    provider: str | None = None
    usage: dict[str, Any] | None = None


@dataclass(frozen=True)
class BridgeConfig:
    bind_host: str = DEFAULT_HOST
    port: int = DEFAULT_PORT
    state_path: Path = DEFAULT_STATE_PATH
    persist_state: bool = True
    token: str | None = None
    hermes_agent_path: Path = Path.home() / ".hermes" / "hermes-agent"
    max_iterations: int = 90
    composio_api_key: str | None = None
    composio_api_base_url: str = "https://backend.composio.dev/api/v1"
    connector_entity_id: str = "diak-local-user"
    connector_redirect_url: str | None = None


class BridgeState:
    """Tiny JSON state store for Diak sessions and captured stream events."""

    def __init__(self, path: Path | None = None, *, persist: bool = True):
        self.path = path or DEFAULT_STATE_PATH
        self.persist = persist
        self._lock = threading.RLock()
        self._data: dict[str, Any] = {"sessions": {}, "messages": {}, "events": {}, "connectors": {}, "artifacts": {}, "approvals": {}, "memory": {}, "automations": {}, "skills": {}, "skill_drafts": {}}
        if persist:
            self._load()

    def _load(self) -> None:
        try:
            if self.path.exists():
                loaded = json.loads(self.path.read_text(encoding="utf-8"))
                if isinstance(loaded, dict):
                    self._data["sessions"] = loaded.get("sessions", {}) if isinstance(loaded.get("sessions", {}), dict) else {}
                    self._data["messages"] = loaded.get("messages", {}) if isinstance(loaded.get("messages", {}), dict) else {}
                    self._data["events"] = loaded.get("events", {}) if isinstance(loaded.get("events", {}), dict) else {}
                    self._data["connectors"] = loaded.get("connectors", {}) if isinstance(loaded.get("connectors", {}), dict) else {}
                    self._data["artifacts"] = loaded.get("artifacts", {}) if isinstance(loaded.get("artifacts", {}), dict) else {}
                    self._data["approvals"] = loaded.get("approvals", {}) if isinstance(loaded.get("approvals", {}), dict) else {}
                    self._data["memory"] = loaded.get("memory", {}) if isinstance(loaded.get("memory", {}), dict) else {}
                    self._data["automations"] = loaded.get("automations", {}) if isinstance(loaded.get("automations", {}), dict) else {}
                    self._data["skills"] = loaded.get("skills", {}) if isinstance(loaded.get("skills", {}), dict) else {}
                    self._data["skill_drafts"] = loaded.get("skill_drafts", {}) if isinstance(loaded.get("skill_drafts", {}), dict) else {}
        except Exception:
            # Corrupt state must not prevent the bridge from starting.  Keep the
            # bad file for forensic inspection and begin with empty state.
            self._data = {"sessions": {}, "messages": {}, "events": {}, "connectors": {}, "artifacts": {}, "approvals": {}, "memory": {}, "automations": {}, "skills": {}, "skill_drafts": {}}

    def _save_locked(self) -> None:
        if not self.persist:
            return
        self.path.parent.mkdir(parents=True, exist_ok=True)
        fd, tmp_name = tempfile.mkstemp(prefix=self.path.name, suffix=".tmp", dir=str(self.path.parent))
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                json.dump(self._data, handle, ensure_ascii=False, indent=2, sort_keys=True)
                handle.write("\n")
            os.replace(tmp_name, self.path)
        finally:
            try:
                if os.path.exists(tmp_name):
                    os.unlink(tmp_name)
            except OSError:
                pass

    def list_sessions(self) -> list[dict[str, Any]]:
        with self._lock:
            return sorted(self._data["sessions"].values(), key=lambda s: s.get("updated_at", ""), reverse=True)

    def get_session(self, session_id: str) -> dict[str, Any] | None:
        with self._lock:
            session = self._data["sessions"].get(session_id)
            return dict(session) if isinstance(session, dict) else None

    def get_messages(self, session_id: str) -> list[dict[str, Any]]:
        with self._lock:
            return list(self._data["messages"].get(session_id, []))

    def get_events(self, session_id: str) -> list[dict[str, Any]]:
        with self._lock:
            return list(self._data["events"].get(session_id, []))

    def get_artifacts(self, session_id: str) -> list[dict[str, Any]]:
        with self._lock:
            return list(self._data["artifacts"].get(session_id, []))

    def upsert_session(self, session: dict[str, Any]) -> dict[str, Any]:
        with self._lock:
            self._data["sessions"][session["id"]] = dict(session)
            self._save_locked()
            return dict(session)

    def append_message(self, session_id: str, message: dict[str, Any]) -> None:
        with self._lock:
            self._data["messages"].setdefault(session_id, []).append(dict(message))
            self._save_locked()

    def set_events(self, session_id: str, events: list[dict[str, Any]]) -> None:
        with self._lock:
            self._data["events"][session_id] = list(events)
            self._save_locked()

    def append_events(self, session_id: str, events: list[dict[str, Any]]) -> None:
        with self._lock:
            self._data["events"].setdefault(session_id, []).extend(events)
            self._save_locked()

    def set_artifacts(self, session_id: str, artifacts: list[dict[str, Any]]) -> None:
        with self._lock:
            self._data["artifacts"][session_id] = list(artifacts)
            self._save_locked()


CONNECTOR_CATALOG: list[dict[str, Any]] = [
    {
        "id": "conn-notion", "kind": "notion", "display_name": "Notion",
        "summary": "Read and update Notion pages/databases after OAuth approval.",
        "status": "not_connected", "sync_status": "never_synced", "write_policy": "always_ask",
        "capabilities": ["read", "write"], "setup_kind": "oauth",
        "scopes": [
            {"id": "notion.read", "display_name": "Read pages", "detail": "Read workspace pages selected during OAuth.", "is_granted": False, "is_required": True},
            {"id": "notion.write", "display_name": "Update pages", "detail": "Create/update pages selected during OAuth.", "is_granted": False, "is_required": False},
        ],
    },
    {
        "id": "conn-slack", "kind": "slack", "display_name": "Slack",
        "summary": "Search Slack and send messages only after Diak approval policy allows it.",
        "status": "not_connected", "sync_status": "never_synced", "write_policy": "always_ask",
        "capabilities": ["read", "send"], "setup_kind": "oauth",
        "scopes": [
            {"id": "channels:history", "display_name": "Read channel history", "detail": "Search/read channels approved in Slack OAuth.", "is_granted": False, "is_required": True},
            {"id": "chat:write", "display_name": "Send messages", "detail": "Send messages after Diak approval.", "is_granted": False, "is_required": False},
        ],
    },
    {
        "id": "conn-github", "kind": "github", "display_name": "GitHub",
        "summary": "Read repositories and open issues/PR comments behind approval gates.",
        "status": "not_connected", "sync_status": "never_synced", "write_policy": "always_ask",
        "capabilities": ["read", "write"], "setup_kind": "oauth",
        "scopes": [
            {"id": "repo:read", "display_name": "Read repositories", "detail": "Read repositories approved during OAuth.", "is_granted": False, "is_required": True},
            {"id": "pull_requests:write", "display_name": "Write PR comments", "detail": "Comment or create PR artifacts after approval.", "is_granted": False, "is_required": False},
        ],
    },
    {
        "id": "conn-gmail", "kind": "gmail", "display_name": "Gmail",
        "summary": "Read Gmail context and draft/send email only through explicit approval.",
        "status": "not_connected", "sync_status": "never_synced", "write_policy": "always_ask",
        "capabilities": ["read", "send"], "setup_kind": "oauth",
        "scopes": [
            {"id": "gmail.readonly", "display_name": "Read mail", "detail": "Search/read mail approved during OAuth.", "is_granted": False, "is_required": True},
            {"id": "gmail.send", "display_name": "Send mail", "detail": "Send email after explicit Diak approval.", "is_granted": False, "is_required": False},
        ],
    },
    {
        "id": "conn-linear", "kind": "linear", "display_name": "Linear",
        "summary": "Read and update Linear issues after OAuth approval.",
        "status": "not_connected", "sync_status": "never_synced", "write_policy": "always_ask",
        "capabilities": ["read", "write"], "setup_kind": "oauth",
        "scopes": [
            {"id": "linear.read", "display_name": "Read workspace", "detail": "Read teams/issues approved during OAuth.", "is_granted": False, "is_required": True},
            {"id": "linear.write", "display_name": "Update issues", "detail": "Create/update issues after approval.", "is_granted": False, "is_required": False},
        ],
    },
    {
        "id": "conn-telegram", "kind": "http", "display_name": "Telegram",
        "summary": "Read Hermes Telegram gateway status and send messages only after explicit Diak approval.",
        "status": "connected", "sync_status": "ok", "write_policy": "always_ask",
        "capabilities": ["read", "send"], "setup_kind": "none",
        "account_label": "Hermes Telegram home channel",
        "scopes": [
            {"id": "telegram.status", "display_name": "Read gateway status", "detail": "Inspect Hermes Telegram delivery availability.", "is_granted": True, "is_required": True},
            {"id": "telegram.send", "display_name": "Send messages", "detail": "Send Telegram messages after explicit approval.", "is_granted": True, "is_required": False},
        ],
    },
]


def connector_toolkit(connector_id: str) -> str:
    return connector_id.removeprefix("conn-").upper().replace("-", "_")


def _parse_hermes_cron_list(output: str) -> list[dict[str, Any]]:
    jobs: list[dict[str, Any]] = []
    current: dict[str, Any] | None = None
    for raw in output.splitlines():
        line = raw.rstrip()
        m = re.match(r"\s*([0-9a-f]{8,}) \[(\w+)\]", line)
        if m:
            if current:
                jobs.append(current)
            current = {"id": m.group(1), "status": "active" if m.group(2) == "active" else "paused"}
            continue
        if current and ":" in line:
            key, val = line.strip().split(":", 1)
            current[key.lower().replace(" ", "_")] = val.strip()
    if current:
        jobs.append(current)
    return jobs

def _run_command(argv: list[str], timeout: int = 30) -> tuple[int, str]:
    try:
        cp = subprocess.run(argv, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=timeout)
        return cp.returncode, cp.stdout
    except Exception as exc:
        return 1, str(exc)

def _skill_category_from_path(path: Path) -> str:
    text = "/".join(path.parts).lower()
    if any(x in text for x in ("coding", "software", "ios", "github")): return "coding"
    if any(x in text for x in ("research", "mlops")): return "research"
    if any(x in text for x in ("devops", "ops")): return "ops"
    if "data" in text: return "data"
    if any(x in text for x in ("plan", "product")): return "planning"
    return "general"

def _extract_frontmatter_field(text: str, field: str, default: str = "") -> str:
    m = re.search(rf"^\s*{re.escape(field)}\s*:\s*[\"]?([^\n\"]+)", text, flags=re.MULTILINE)
    return m.group(1).strip().strip("'") if m else default

class ConnectorRegistry:
    def __init__(self, state: BridgeState, config: BridgeConfig):
        self.state = state
        self.config = config

    def _overlay(self) -> dict[str, dict[str, Any]]:
        with self.state._lock:
            return self.state._data.setdefault("connectors", {})

    def _merged(self, connector_id: str) -> dict[str, Any] | None:
        base = next((dict(c) for c in CONNECTOR_CATALOG if c["id"] == connector_id), None)
        if not base:
            return None
        with self.state._lock:
            overlay = dict(self.state._data.setdefault("connectors", {}).get(connector_id, {}))
        base.update(overlay)
        return base

    def list(self) -> dict[str, Any]:
        connectors = [self._merged(c["id"]) for c in CONNECTOR_CATALOG]
        connectors = [c for c in connectors if c]
        connectors.sort(key=lambda c: (0 if c.get("status") == "connected" else 1, c.get("display_name", "")))
        configured = bool(self.config.composio_api_key or os.getenv("DIAK_CONNECTOR_SETUP_URL_TEMPLATE"))
        note = "Connectors are wired to the production Diak bridge. Click Connect to open provider OAuth; tokens never enter the desktop app."
        if not configured:
            note += " Provider credentials are not configured yet, so setup will report configuration-required instead of faking success."
        return {"connectors": connectors, "boundary_note": note}

    def get(self, connector_id: str) -> dict[str, Any] | None:
        return self._merged(connector_id)

    def update_policy(self, connector_id: str, policy: str) -> dict[str, Any] | None:
        connector = self._merged(connector_id)
        if not connector:
            return None
        with self.state._lock:
            self.state._data.setdefault("connectors", {}).setdefault(connector_id, {})["write_policy"] = policy
            self.state._save_locked()
        connector["write_policy"] = policy
        return {"connector": connector, "note": f"Write policy set to {policy}. High-risk writes remain approval gated."}

    def disconnect(self, connector_id: str) -> dict[str, Any] | None:
        connector = self._merged(connector_id)
        if not connector:
            return None
        with self.state._lock:
            self.state._data.setdefault("connectors", {})[connector_id] = {
                "status": "not_connected", "sync_status": "never_synced", "account_label": None,
                "last_synced_at": None, "last_error": None, "pending_approval_id": None,
            }
            self.state._save_locked()
        return {"disconnected": True, "id": connector_id, "note": "Connector disconnected in Diak bridge state. Revoke provider tokens in the provider dashboard if needed."}

    def begin_setup(self, connector_id: str) -> tuple[int, dict[str, Any]]:
        connector = self._merged(connector_id)
        if not connector:
            return 404, {"error": {"message": "Connector not found", "type": "not_found"}}
        approval_id = make_id("appr-conn-setup")
        setup_url = self._configured_setup_url(connector)
        if not setup_url:
            with self.state._lock:
                self.state._data.setdefault("connectors", {}).setdefault(connector_id, {}).update({
                    "status": "error", "sync_status": "error",
                    "last_error": "Connector provider not configured. Set COMPOSIO_API_KEY plus a Composio setup URL/template, or DIAK_CONNECTOR_SETUP_URL_TEMPLATE.",
                    "pending_approval_id": approval_id,
                })
                self.state._save_locked()
            return 200, {
                "connector_id": connector_id,
                "setup_kind": connector.get("setup_kind", "oauth"),
                "state": "configuration_required",
                "message": "Connector provider is not configured on this Mac. Diak did not fake an OAuth flow.",
                "approval_id": approval_id,
            }
        with self.state._lock:
            self.state._data.setdefault("connectors", {}).setdefault(connector_id, {}).update({
                "status": "pending", "sync_status": "syncing", "last_error": None, "pending_approval_id": approval_id,
            })
            self.state._save_locked()
        return 200, {
            "connector_id": connector_id,
            "setup_kind": connector.get("setup_kind", "oauth"),
            "state": "awaiting_oauth",
            "message": "Approve the provider OAuth request in your browser. Diak will refresh connection status from the bridge after authorization.",
            "setup_url": setup_url,
            "approval_id": approval_id,
        }

    def _configured_setup_url(self, connector: dict[str, Any]) -> str | None:
        connector_id = connector["id"]
        toolkit = connector_toolkit(connector_id)
        direct = os.getenv(f"DIAK_CONNECTOR_SETUP_URL_{connector_id.upper().replace('-', '_')}")
        template = os.getenv("DIAK_CONNECTOR_SETUP_URL_TEMPLATE")
        if direct:
            return direct
        if template:
            return template.format(
                connector_id=connector_id,
                toolkit=toolkit,
                entity_id=self.config.connector_entity_id,
                redirect_url=self.config.connector_redirect_url or "",
            )
        # Composio's hosted-connect URL format varies by account/API version. Keep
        # this explicit instead of guessing a fake OAuth URL when no template has
        # been provided by release configuration.
        return None


class HermesAgentRuntime:
    """Adapter around the real Hermes Agent runtime used by gateway platforms."""

    def __init__(self, config: BridgeConfig):
        self.config = config
        agent_path = str(config.hermes_agent_path.expanduser())
        if agent_path not in sys.path:
            sys.path.insert(0, agent_path)

    def run(
        self,
        prompt: str,
        *,
        history: list[dict[str, str]],
        preferred_session_id: str | None = None,
        stream_callback: Callable[[str], None] | None = None,
    ) -> RuntimeResult:
        from gateway.run import GatewayRunner, _resolve_gateway_model, _resolve_runtime_agent_kwargs
        from run_agent import AIAgent

        runtime_kwargs = _resolve_runtime_agent_kwargs()
        model = _resolve_gateway_model()
        agent = AIAgent(
            model=model,
            **runtime_kwargs,
            max_iterations=self.config.max_iterations,
            quiet_mode=True,
            verbose_logging=False,
            enabled_toolsets=[],
            session_id=preferred_session_id,
            platform="diak",
            reasoning_config=GatewayRunner._load_reasoning_config(),
            fallback_model=GatewayRunner._load_fallback_model(),
        )
        result = agent.run_conversation(
            prompt,
            conversation_history=history,
            task_id=f"diak-{uuid.uuid4().hex[:12]}",
            stream_callback=stream_callback,
        )
        if result.get("failed"):
            raise RuntimeError(result.get("error") or "Hermes runtime failed")
        text = (result.get("final_response") or "").strip()
        if not text:
            raise RuntimeError(result.get("error") or "Hermes runtime returned an empty response")
        return RuntimeResult(
            text=text,
            hermes_session_id=result.get("session_id") or getattr(agent, "session_id", None),
            model=result.get("model") or model,
            provider=result.get("provider") or runtime_kwargs.get("provider"),
            usage={
                key: result.get(key)
                for key in ("input_tokens", "output_tokens", "total_tokens", "estimated_cost_usd")
                if key in result
            },
        )


class DiakHermesBridgeServer(ThreadingHTTPServer):
    daemon_threads = True
    allow_reuse_address = True

    def __init__(self, server_address, *, runtime: Any, state: BridgeState, config: BridgeConfig):
        self.runtime = runtime
        self.state = state
        self.config = config
        self.connectors = ConnectorRegistry(state, config)
        super().__init__(server_address, DiakHermesBridgeHandler)


class DiakHermesBridgeHandler(BaseHTTPRequestHandler):
    server: DiakHermesBridgeServer
    protocol_version = "HTTP/1.1"

    def log_message(self, fmt: str, *args: Any) -> None:
        sys.stderr.write("[%s] %s\n" % (utc_now(), fmt % args))

    # ---------- response helpers ----------
    def _send_json(self, status: int, payload: Any, headers: dict[str, str] | None = None) -> None:
        body = json_dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        for key, value in (headers or {}).items():
            self.send_header(key, value)
        self.end_headers()
        self.wfile.write(body)

    def _send_error(self, status: int, message: str, *, details: str | None = None) -> None:
        payload = {"error": {"message": message, "type": HTTPStatus(status).phrase.lower().replace(" ", "_")}}
        if details:
            payload["error"]["details"] = details
        self._send_json(status, payload)

    def _authorized(self) -> bool:
        token = self.server.config.token
        if not token:
            return True
        expected = f"Bearer {token}"
        if self.headers.get("Authorization") == expected:
            return True
        self._send_error(401, "Unauthorized")
        return False

    def _read_json_body(self) -> dict[str, Any] | None:
        try:
            length = int(self.headers.get("Content-Length", "0"))
        except ValueError:
            self._send_error(400, "Invalid Content-Length")
            return None
        if length > MAX_BODY_BYTES:
            self._send_error(413, "Request body too large")
            return None
        raw = self.rfile.read(length) if length else b"{}"
        try:
            payload = json.loads(raw.decode("utf-8")) if raw else {}
        except Exception:
            self._send_error(400, "Invalid JSON request body")
            return None
        if not isinstance(payload, dict):
            self._send_error(400, "JSON body must be an object")
            return None
        return payload

    # ---------- routes ----------
    def do_GET(self) -> None:  # noqa: N802
        if not self._authorized():
            return
        path = urlparse(self.path).path.rstrip("/") or "/"
        try:
            if path == "/health":
                return self._send_json(200, {"status": "ok", "message": "Diak production Hermes bridge ready"})
            if path == "/version":
                return self._send_json(200, self._version_payload())
            if path == "/config":
                return self._send_json(200, self._config_snapshot())
            if path == "/daemon/logs":
                return self._send_json(200, self._daemon_summary())
            if path == "/sessions":
                return self._send_json(200, self.server.state.list_sessions())
            if path.startswith("/sessions/"):
                return self._handle_get_session_path(path)
            if path == "/connectors":
                return self._send_json(200, self.server.connectors.list())
            if path == "/settings/secrets":
                return self._send_json(200, self._settings_secrets_metadata())
            if path == "/approvals":
                return self._send_json(200, self._list_approvals())
            if path == "/evidence":
                return self._send_json(200, self._list_evidence())
            match = re.fullmatch(r"/approvals/([^/]+)", path)
            if match:
                approval = self._get_approval(match.group(1))
                if not approval:
                    return self._send_error(404, "Approval not found")
                return self._send_json(200, approval)
            if path == "/automations":
                return self._send_json(200, self._list_automations())
            if path == "/memory":
                return self._send_json(200, self._memory_dashboard())
            match = re.fullmatch(r"/memory/([^/]+)", path)
            if match:
                item = self._get_memory(match.group(1))
                if not item:
                    return self._send_error(404, "Memory not found")
                return self._send_json(200, item)
            if path == "/skills":
                return self._send_json(200, self._skills_catalog())
            match = re.fullmatch(r"/skills/([^/]+)", path)
            if match:
                skill = self._get_skill(match.group(1))
                if not skill:
                    return self._send_error(404, "Skill not found")
                return self._send_json(200, skill)
            match = re.fullmatch(r"/connectors/([^/]+)", path)
            if match:
                connector = self.server.connectors.get(match.group(1))
                if not connector:
                    return self._send_error(404, "Connector not found")
                return self._send_json(200, connector)
            return self._send_error(404, "Not found")
        except BrokenPipeError:
            return
        except Exception as exc:
            traceback.print_exc()
            return self._send_error(500, "Bridge request failed", details=str(exc))

    def do_POST(self) -> None:  # noqa: N802
        if not self._authorized():
            return
        path = urlparse(self.path).path.rstrip("/") or "/"
        body = self._read_json_body()
        if body is None:
            return
        try:
            if path == "/config":
                return self._update_config(body)
            if path in ("/daemon/restart", "/daemon/reconnect"):
                return self._send_json(200, {"accepted": True, "note": "Diak production bridge accepted the lifecycle request. Restart/reconnect is managed by the macOS app launcher."})
            if path == "/sessions":
                return self._create_session(body)
            match = re.fullmatch(r"/sessions/([^/]+)/messages", path)
            if match:
                return self._continue_session(match.group(1), body)
            match = re.fullmatch(r"/connectors/([^/]+)/setup", path)
            if match:
                status, payload = self.server.connectors.begin_setup(match.group(1))
                return self._send_json(status, payload)
            match = re.fullmatch(r"/connectors/([^/]+)/actions/send", path)
            if match:
                return self._queue_connector_send(match.group(1), body)
            match = re.fullmatch(r"/approvals/([^/]+)/decision", path)
            if match:
                return self._decide_approval(match.group(1), body)
            if path == "/automations":
                return self._create_automation(body)
            match = re.fullmatch(r"/automations/([^/]+)/test-run", path)
            if match:
                return self._run_automation(match.group(1))
            match = re.fullmatch(r"/automations/([^/]+)/(pause|resume)", path)
            if match:
                return self._set_automation_status(match.group(1), "paused" if match.group(2) == "pause" else "active")
            if path == "/memory":
                return self._create_memory(body)
            if path == "/skills/draft":
                return self._create_skill_draft(body)
            return self._send_error(404, "Not found")
        except Exception as exc:
            traceback.print_exc()
            return self._send_error(500, "Hermes runtime request failed", details=str(exc))

    def do_PATCH(self) -> None:  # noqa: N802
        if not self._authorized():
            return
        path = urlparse(self.path).path.rstrip("/") or "/"
        body = self._read_json_body()
        if body is None:
            return
        match = re.fullmatch(r"/automations/([^/]+)", path)
        if match:
            return self._update_automation(match.group(1), body)
        match = re.fullmatch(r"/memory/([^/]+)", path)
        if match:
            return self._update_memory(match.group(1), body)
        match = re.fullmatch(r"/skills/([^/]+)/enabled", path)
        if match:
            return self._set_skill_enabled(match.group(1), bool(body.get("is_enabled")))
        match = re.fullmatch(r"/connectors/([^/]+)/policy", path)
        if match:
            policy = str(body.get("write_policy") or "always_ask")
            result = self.server.connectors.update_policy(match.group(1), policy)
            if not result:
                return self._send_error(404, "Connector not found")
            return self._send_json(200, result)
        return self._send_error(404, "Not found")

    def do_DELETE(self) -> None:  # noqa: N802
        if not self._authorized():
            return
        path = urlparse(self.path).path.rstrip("/") or "/"
        match = re.fullmatch(r"/automations/([^/]+)", path)
        if match:
            return self._delete_automation(match.group(1))
        match = re.fullmatch(r"/memory/([^/]+)", path)
        if match:
            return self._delete_memory(match.group(1))
        match = re.fullmatch(r"/connectors/([^/]+)", path)
        if match:
            result = self.server.connectors.disconnect(match.group(1))
            if not result:
                return self._send_error(404, "Connector not found")
            return self._send_json(200, result)
        return self._send_error(404, "Not found")


    def _list_approvals(self) -> list[dict[str, Any]]:
        with self.server.state._lock:
            vals = list(self.server.state._data.setdefault("approvals", {}).values())
        vals.sort(key=lambda a: a.get("created_at", ""), reverse=True)
        return vals

    def _get_approval(self, approval_id: str) -> dict[str, Any] | None:
        with self.server.state._lock:
            approval = self.server.state._data.setdefault("approvals", {}).get(approval_id)
            return dict(approval) if isinstance(approval, dict) else None

    def _list_evidence(self, session_id: str | None = None) -> list[dict[str, Any]]:
        with self.server.state._lock:
            approvals = list(self.server.state._data.setdefault("approvals", {}).values())
        evidence: list[dict[str, Any]] = []
        for approval in approvals:
            if not isinstance(approval, dict):
                continue
            status = str(approval.get("status") or "pending").lower()
            if status == "pending":
                continue
            if session_id is not None and approval.get("session_id") != session_id:
                continue
            action_type = str(approval.get("action_type") or "action")
            title = str(approval.get("title") or "Action")
            occurred_at = str(approval.get("updated_at") or approval.get("created_at") or utc_now())
            evidence_status = {
                "approved": "completed",
                "denied": "denied",
                "failed": "failed",
                "cancelled": "cancelled",
            }.get(status, "completed")
            payload_preview = approval.get("payload_preview") if isinstance(approval.get("payload_preview"), dict) else {}
            artifacts = []
            execution_result = approval.get("execution_result") if isinstance(approval.get("execution_result"), dict) else {}
            provider_result = execution_result.get("provider_result") if isinstance(execution_result.get("provider_result"), dict) else {}
            if action_type == "connector_send":
                target = str(payload_preview.get("target") or "telegram")
                artifacts.append({
                    "id": f"artifact-{approval.get('id')}-message",
                    "kind": "message",
                    "title": target,
                    "detail": "Queued and executed through Hermes send_message after Diak approval" if evidence_status == "completed" else "Connector action did not complete",
                })
            if provider_result.get("url"):
                artifacts.append({
                    "id": f"artifact-{approval.get('id')}-link",
                    "kind": "link",
                    "title": "Provider result",
                    "detail": str(provider_result.get("url")),
                })
            evidence.append({
                "id": f"ev-{approval.get('id')}",
                "title": title,
                "summary": approval.get("summary") or approval.get("decision_note"),
                "status": evidence_status,
                "occurred_at": occurred_at,
                "actor": "Diak",
                "tool_name": action_type,
                "approval_id": approval.get("id"),
                "session_id": approval.get("session_id"),
                "artifacts": artifacts,
            })
        evidence.sort(key=lambda item: item.get("occurred_at", ""), reverse=True)
        return evidence

    def _store_approval(self, approval: dict[str, Any]) -> dict[str, Any]:
        with self.server.state._lock:
            self.server.state._data.setdefault("approvals", {})[approval["id"]] = dict(approval)
            self.server.state._save_locked()
        return approval

    def _queue_connector_send(self, connector_id: str, body: dict[str, Any]) -> None:
        connector = self.server.connectors.get(connector_id)
        if not connector:
            return self._send_error(404, "Connector not found")
        if connector_id != "conn-telegram":
            return self._send_error(400, "Only Telegram send is implemented in this Diak bridge slice")
        message = str(body.get("message") or "").strip()
        target = str(body.get("target") or "telegram").strip() or "telegram"
        if not message:
            return self._send_error(400, "Missing message")
        approval_id = make_id("appr-telegram-send")
        now = utc_now()
        approval = {
            "id": approval_id, "title": "Send Telegram message", "summary": message[:240],
            "risk": "medium", "status": "pending", "created_at": now, "updated_at": now,
            "session_id": None, "action_type": "connector_send", "target": target,
            "payload_preview": {"connector_id": connector_id, "target": target, "message": message},
            "decision_note": None,
        }
        self._store_approval(approval)
        with self.server.state._lock:
            self.server.state._data.setdefault("connectors", {}).setdefault(connector_id, {}).update({"pending_approval_id": approval_id, "status": "connected", "sync_status": "ok"})
            self.server.state._save_locked()
        return self._send_json(200, {"approval": approval, "note": "Telegram send queued for explicit approval; no message sent yet."})

    def _decide_approval(self, approval_id: str, body: dict[str, Any]) -> None:
        approval = self._get_approval(approval_id)
        if not approval:
            return self._send_error(404, "Approval not found")
        decision = str(body.get("decision") or "").lower()
        if decision not in ("approved", "denied", "approve", "deny"):
            return self._send_error(400, "Decision must be approved or denied")
        approved = decision in ("approved", "approve")
        note = str(body.get("note") or "").strip() or None
        approval["status"] = "approved" if approved else "denied"
        approval["decision_note"] = note
        approval["updated_at"] = utc_now()
        if approved and approval.get("action_type") == "connector_send":
            payload = approval.get("payload_preview") or {}
            sent = self._send_telegram_via_hermes(str(payload.get("target") or "telegram"), str(payload.get("message") or ""))
            approval["execution_result"] = sent
            if not sent.get("success"):
                approval["status"] = "failed"
        self._store_approval(approval)
        return self._send_json(200, approval)

    def _send_telegram_via_hermes(self, target: str, message: str) -> dict[str, Any]:
        agent_path = str(self.server.config.hermes_agent_path.expanduser())
        if agent_path not in sys.path:
            sys.path.insert(0, agent_path)
        try:
            from tools.send_message_tool import send_message_tool
            raw = send_message_tool({"action": "send", "target": target, "message": message})
            payload = json.loads(raw) if isinstance(raw, str) else raw
            ok = not (isinstance(payload, dict) and payload.get("error"))
            return {"success": bool(ok), "provider_result": payload}
        except Exception as exc:
            return {"success": False, "error": str(exc)}

    def _daemon_summary(self) -> dict[str, Any]:
        version = self._version_payload()
        return {
            "version": version.get("version"),
            "build": version.get("build"),
            "profile": version.get("profile"),
            "uptime_seconds": None,
            "log_path": str(self.server.config.state_path),
            "recent_lines": [
                "Diak production Hermes bridge ready",
                f"state={self.server.config.state_path}",
            ],
            "last_checked_at": utc_now(),
        }

    def _default_config_snapshot(self) -> dict[str, Any]:
        version = self._version_payload()
        provider = version.get("provider") or os.getenv("HERMES_PROVIDER") or "configured"
        model = version.get("model") or os.getenv("HERMES_MODEL") or "Hermes default"
        return {
            "profiles": [
                {
                    "id": "prof-default",
                    "display_name": os.getenv("USER") or "Diak User",
                    "role": "engineer",
                    "default_project_label": "HermesDesktop",
                    "is_active": True,
                }
            ],
            "active_profile_id": "prof-default",
            "providers": [
                {
                    "id": "prov-hermes-runtime",
                    "display_name": "Hermes Runtime",
                    "kind": "other",
                    "status": "ready",
                    "default_model": model,
                    "available_models": [model] if model else [],
                    "needs_api_key": False,
                    "has_api_key": True,
                    "restart_required": False,
                }
            ],
            "tools": [
                {
                    "id": "tool-terminal",
                    "name": "Terminal",
                    "description": "Run local commands through Hermes Agent after approval gates.",
                    "can_read": True,
                    "can_write": True,
                    "can_destroy": True,
                    "policy": "always_ask",
                    "is_enabled": True,
                    "restart_required": False,
                },
                {
                    "id": "tool-connectors",
                    "name": "Connectors",
                    "description": "Read connector status and queue writes behind Diak approval.",
                    "can_read": True,
                    "can_write": True,
                    "can_destroy": False,
                    "policy": "always_ask",
                    "is_enabled": True,
                    "restart_required": False,
                },
                {
                    "id": "tool-automations",
                    "name": "Automations",
                    "description": "Create and run Hermes cron-backed automations.",
                    "can_read": True,
                    "can_write": True,
                    "can_destroy": False,
                    "policy": "always_ask",
                    "is_enabled": True,
                    "restart_required": False,
                },
            ],
            "security": {
                "trusted_folders": [
                    {"id": "fold-hermes-desktop", "path": str(Path.cwd()), "allows_writes": True}
                ],
                "log_redaction": "strict",
                "log_retention_days": 14,
                "telemetry_enabled": False,
                "offline_mode_enabled": False,
                "restart_required": False,
            },
            "daemon": self._daemon_summary(),
        }

    def _config_snapshot(self) -> dict[str, Any]:
        with self.server.state._lock:
            stored = self.server.state._data.setdefault("config", {})
            if not stored:
                stored.update(self._default_config_snapshot())
                self.server.state._save_locked()
            snapshot = json.loads(json_dumps(stored))
        snapshot["daemon"] = self._daemon_summary()
        return snapshot

    def _update_config(self, body: dict[str, Any]) -> None:
        allowed = {"active_profile", "providers", "tools", "security"}
        if not any(key in body for key in allowed):
            return self._send_error(400, "Empty config update")
        with self.server.state._lock:
            current = self.server.state._data.setdefault("config", {})
            if not current:
                current.update(self._default_config_snapshot())
            requires_restart = False
            if isinstance(body.get("active_profile"), dict):
                profile = dict(body["active_profile"])
                profile["is_active"] = True
                current["active_profile_id"] = profile.get("id") or current.get("active_profile_id")
                profiles = [p for p in current.get("profiles", []) if p.get("id") != profile.get("id")]
                for p in profiles:
                    p["is_active"] = False
                current["profiles"] = [profile] + profiles
            if isinstance(body.get("providers"), list):
                current["providers"] = body["providers"]
                requires_restart = True
            if isinstance(body.get("tools"), list):
                current["tools"] = body["tools"]
                requires_restart = True
            if isinstance(body.get("security"), dict):
                current["security"] = body["security"]
                requires_restart = True
            current["daemon"] = self._daemon_summary()
            self.server.state._save_locked()
            snapshot = json.loads(json_dumps(current))
        snapshot["daemon"] = self._daemon_summary()
        return self._send_json(200, {
            "snapshot": snapshot,
            "requires_restart": requires_restart,
            "note": "Config saved in Diak bridge overlay; Hermes runtime remains daemon-owned.",
        })

    def _list_automations(self) -> list[dict[str, Any]]:
        with self.server.state._lock:
            jobs = list(self.server.state._data.setdefault("automations", {}).values())
        # Refresh with Hermes cron CLI metadata when available.
        rc, out = _run_command(["hermes", "cron", "list"], timeout=15)
        if rc == 0:
            cron = {j["id"]: j for j in _parse_hermes_cron_list(out)}
            for job in jobs:
                cid = job.get("cron_job_id")
                if cid and cid in cron:
                    job["status"] = cron[cid].get("status", job.get("status", "active"))
                    job["next_run_at"] = cron[cid].get("next_run") or job.get("next_run_at")
        jobs.sort(key=lambda j: j.get("updated_at", ""), reverse=True)
        return jobs

    def _automation_payload(self, job_id: str, title: str, prompt: str, cron: str, human: str, status: str = "active", cron_job_id: str | None = None, run_history: list[dict[str, Any]] | None = None) -> dict[str, Any]:
        now = utc_now()
        return {"id": job_id, "title": title, "prompt": prompt,
                "schedule": {"cron": cron, "human_description": human, "timezone": os.getenv("TZ", "local")},
                "status": status, "project": None, "created_at": now, "updated_at": now, "next_run_at": None,
                "last_run": (run_history or [None])[-1], "run_history": run_history or [],
                "notification_status": "enabled", "notification_summary": "Managed by Hermes cron when cron_job_id is present.",
                "model_override": None, "cron_job_id": cron_job_id}

    def _create_automation(self, body: dict[str, Any]) -> None:
        title = str(body.get("title") or "").strip()
        prompt = str(body.get("prompt") or "").strip()
        schedule = body.get("schedule") or {}
        cron = str(schedule.get("cron") or "").strip()
        human = str(schedule.get("human_description") or cron).strip() or cron
        if not (title and prompt and cron):
            return self._send_error(400, "Missing automation title, prompt, or schedule")
        cron_job_id = None
        rc, out = _run_command(["hermes", "cron", "create", cron, prompt, "--name", f"diak-{title}", "--deliver", "local", "--repeat", "1"], timeout=30)
        if rc == 0:
            m = re.search(r"([0-9a-f]{8,})", out)
            cron_job_id = m.group(1) if m else None
        job = self._automation_payload(make_id("auto"), title, prompt, cron, human, cron_job_id=cron_job_id)
        if not cron_job_id:
            job["notification_summary"] = f"Hermes cron CLI create failed; stored in Diak bridge only: {out[:200]}"
        with self.server.state._lock:
            self.server.state._data.setdefault("automations", {})[job["id"]] = job
            self.server.state._save_locked()
        return self._send_json(200, {"job": job, "note": "Automation created through Hermes cron." if cron_job_id else "Automation stored; Hermes cron create failed."})

    def _update_automation(self, job_id: str, body: dict[str, Any]) -> None:
        with self.server.state._lock:
            job = self.server.state._data.setdefault("automations", {}).get(job_id)
            if not job: return self._send_error(404, "Automation not found")
            for key in ("title", "prompt"):
                if key in body and body[key] is not None: job[key] = str(body[key])
            if isinstance(body.get("schedule"), dict): job["schedule"].update(body["schedule"])
            job["updated_at"] = utc_now(); self.server.state._save_locked()
        return self._send_json(200, {"job": job, "note": "Automation updated in Diak bridge; recreate cron job for schedule changes."})

    def _run_automation(self, job_id: str) -> None:
        with self.server.state._lock:
            job = self.server.state._data.setdefault("automations", {}).get(job_id)
        if not job: return self._send_error(404, "Automation not found")
        started = utc_now(); lines=[]; status="succeeded"
        cid = job.get("cron_job_id")
        if cid:
            rc, out = _run_command(["hermes", "cron", "run", cid], timeout=30)
            lines = out.splitlines()[-20:]
            if rc != 0: status="failed"
        else:
            try:
                result = self.server.runtime.run(job.get("prompt", ""), history=[], stream_callback=None)
                lines=[result.text[:1000]]
            except Exception as exc:
                status="failed"; lines=[str(exc)]
        run={"id": make_id("run"), "automation_id": job_id, "status": status, "started_at": started, "finished_at": utc_now(), "summary": (lines[-1] if lines else status)[:240], "log_preview": lines}
        with self.server.state._lock:
            job.setdefault("run_history", []).append(run); job["last_run"]=run; job["updated_at"]=utc_now(); self.server.state._save_locked()
        return self._send_json(200, run)

    def _set_automation_status(self, job_id: str, status: str) -> None:
        with self.server.state._lock:
            job = self.server.state._data.setdefault("automations", {}).get(job_id)
            if not job: return self._send_error(404, "Automation not found")
            job["status"] = status; job["updated_at"] = utc_now(); self.server.state._save_locked()
        return self._send_json(200, {"job": job, "note": f"Automation {status}."})

    def _delete_automation(self, job_id: str) -> None:
        with self.server.state._lock:
            job = self.server.state._data.setdefault("automations", {}).pop(job_id, None); self.server.state._save_locked()
        return self._send_json(200, {"deleted": bool(job), "id": job_id, "note": "Automation removed from Diak bridge. Remove paired Hermes cron job from Cron UI if needed."})

    def _memory_dashboard(self) -> dict[str, Any]:
        with self.server.state._lock:
            items = list(self.server.state._data.setdefault("memory", {}).values())
        items.sort(key=lambda i: (not i.get("is_pinned", False), i.get("updated_at", "")), reverse=False)
        return {"items": items, "boundary_note": f"Diak bridge memory is persisted at {self.server.config.state_path} and survives bridge/app restart.", "pinned_count": sum(1 for i in items if i.get("is_pinned")), "total_count": len(items)}

    def _get_memory(self, item_id: str) -> dict[str, Any] | None:
        with self.server.state._lock:
            item = self.server.state._data.setdefault("memory", {}).get(item_id)
            return dict(item) if isinstance(item, dict) else None

    def _create_memory(self, body: dict[str, Any]) -> None:
        title = str(body.get("title") or "").strip(); text = str(body.get("body") or "").strip()
        if not (title and text): return self._send_error(400, "Missing title or body")
        now=utc_now(); item={"id": make_id("mem"), "title": title, "body": text, "scope": str(body.get("scope") or "user"), "source": "manual", "confidence": "high", "tags": body.get("tags") if isinstance(body.get("tags"), list) else [], "project_ref": None, "session_id": None, "created_at": now, "updated_at": now, "is_pinned": bool(body.get("is_pinned"))}
        with self.server.state._lock:
            self.server.state._data.setdefault("memory", {})[item["id"]]=item; self.server.state._save_locked()
        return self._send_json(200, {"item": item, "note": "Memory added and persisted by Diak bridge."})

    def _update_memory(self, item_id: str, body: dict[str, Any]) -> None:
        if not body.get("acknowledged_review", False): return self._send_error(400, "Memory update requires acknowledged_review")
        with self.server.state._lock:
            item = self.server.state._data.setdefault("memory", {}).get(item_id)
            if not item: return self._send_error(404, "Memory not found")
            for key in ("title", "body", "scope"):
                if key in body and body[key] is not None: item[key] = str(body[key])
            if "is_pinned" in body and body["is_pinned"] is not None: item["is_pinned"] = bool(body["is_pinned"])
            item["updated_at"] = utc_now(); self.server.state._save_locked()
        return self._send_json(200, {"item": item, "note": "Memory updated and persisted by Diak bridge."})

    def _delete_memory(self, item_id: str) -> None:
        with self.server.state._lock:
            item = self.server.state._data.setdefault("memory", {}).pop(item_id, None); self.server.state._save_locked()
        return self._send_json(200, {"deleted": bool(item), "id": item_id, "note": "Memory deleted from Diak bridge persistence."})

    def _skills_catalog(self) -> dict[str, Any]:
        skills=[]; seen: set[str] = set(); root=Path.home()/".hermes"/"skills"
        if root.exists():
            for path in root.rglob("SKILL.md"):
                try:
                    text=path.read_text(encoding="utf-8", errors="ignore")
                    name=_extract_frontmatter_field(text,"name", path.parent.name)
                    sid=name
                    with self.server.state._lock:
                        enabled=self.server.state._data.setdefault("skills", {}).get(sid, {}).get("is_enabled", True)
                    skills.append({"id": sid, "name": name, "summary": _extract_frontmatter_field(text,"description", "Hermes skill"), "status": "active" if enabled else "disabled", "category": _skill_category_from_path(path), "source": "user_created", "risk_style": "requires_approval", "version": _extract_frontmatter_field(text,"version", "1.0.0"), "trigger_summary": _extract_frontmatter_field(text,"description", "Loaded when relevant."), "usage_notes": str(path), "artifacts": [], "is_enabled": bool(enabled), "source_session_id": None, "updated_at": None, "installed_by": "Hermes Agent"})
                    seen.add(sid)
                except Exception: pass
        with self.server.state._lock:
            drafts = dict(self.server.state._data.get("skill_drafts", {}))
        for sid, draft in drafts.items():
            if sid in seen: continue
            skills.append(draft)
        skills.sort(key=lambda x: x["name"])
        draft_count = sum(1 for s in skills if s.get("status") == "draft")
        return {"skills": skills, "boundary_note": "Live Hermes skill library scanned from ~/.hermes/skills; enable state and drafts persisted by Diak bridge.", "active_count": sum(1 for s in skills if s["is_enabled"]), "draft_count": draft_count, "total_count": len(skills)}

    def _get_skill(self, skill_id: str) -> dict[str, Any] | None:
        return next((s for s in self._skills_catalog()["skills"] if s["id"] == skill_id), None)

    def _create_skill_draft(self, body: dict[str, Any]) -> None:
        # Direct add path: the desktop UI authors a skill draft without an
        # existing chat session. The bridge persists the draft as a
        # boundary record so the catalog reflects it; Hermes Agent owns
        # the actual install/execution side effect.
        if not bool(body.get("acknowledged_daemon_install")):
            return self._send_error(400, "acknowledged_daemon_install must be true")
        name = str(body.get("name") or "").strip()
        summary = str(body.get("summary") or "").strip()
        trigger = str(body.get("trigger_summary") or "").strip()
        if not name or not summary or not trigger:
            return self._send_error(400, "name, summary, and trigger_summary are required")
        category = str(body.get("category") or "general").strip().lower() or "general"
        risk_style = str(body.get("risk_style") or "requires_approval").strip().lower() or "requires_approval"
        instructions_raw = body.get("instructions")
        instructions = str(instructions_raw).strip() if isinstance(instructions_raw, str) else ""
        slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
        skill_id = f"skill-direct-{slug}" if slug else f"skill-direct-{int(time.time())}"
        # Avoid collisions with existing on-disk skills or prior drafts.
        if self._get_skill(skill_id) is not None:
            skill_id = f"{skill_id}-{int(time.time())}"
        artifacts: list[dict[str, Any]] = []
        if instructions:
            artifacts.append({
                "id": f"art-instructions-{skill_id}",
                "kind": "prompt_template",
                "title": "Authoring instructions",
                "detail": instructions,
            })
        skill = {
            "id": skill_id,
            "name": name,
            "summary": summary,
            "status": "draft",
            "category": category,
            "source": "user_created",
            "risk_style": risk_style,
            "version": "0.1.0",
            "trigger_summary": trigger,
            "usage_notes": "Draft authored from the Skills screen. Hermes Agent finalises install in the background.",
            "artifacts": artifacts,
            "is_enabled": False,
            "source_session_id": None,
            "updated_at": None,
            "installed_by": "Hermes Agent",
        }
        with self.server.state._lock:
            self.server.state._data.setdefault("skill_drafts", {})[skill_id] = skill
            self.server.state._save_locked()
        return self._send_json(200, {
            "skill": skill,
            "note": "Skill draft submitted. Hermes Agent owns install and execution.",
        })

    def _set_skill_enabled(self, skill_id: str, enabled: bool) -> None:
        skill = self._get_skill(skill_id)
        if not skill: return self._send_error(404, "Skill not found")
        with self.server.state._lock:
            self.server.state._data.setdefault("skills", {}).setdefault(skill_id, {})["is_enabled"] = enabled; self.server.state._save_locked()
        skill["is_enabled"] = enabled; skill["status"] = "active" if enabled else "disabled"
        return self._send_json(200, {"skill": skill, "note": "Skill enable state saved in Diak bridge overlay."})

    def _settings_secrets_metadata(self) -> dict[str, Any]:
        """Return the Settings secrets catalog. Never returns raw values.

        Slice 3 boundary: the bridge does not own the Keychain. Diak (the macOS
        app) writes secrets to the Keychain and injects them into the bridge's
        env at launch. This endpoint reports descriptor + presence metadata so
        the Settings UI can render editable fields and "Saved" / "Missing"
        badges without ever round-tripping a raw API key.
        """
        api_key_present = bool(os.getenv("COMPOSIO_API_KEY") or self.server.config.composio_api_key)
        non_sensitive_fields: list[str] = []
        # Mirror the field ids the Mac app's HermesSecretDescriptor exposes for
        # the Composio slot. Each entry is metadata only.
        non_sensitive_env_map = [
            ("base_url", "COMPOSIO_API_BASE_URL"),
            ("entity_id", "DIAK_CONNECTOR_ENTITY_ID"),
            ("redirect_url", "DIAK_CONNECTOR_REDIRECT_URL"),
            ("setup_url_template", "DIAK_CONNECTOR_SETUP_URL_TEMPLATE"),
        ]
        for field_id, env_name in non_sensitive_env_map:
            value = os.getenv(env_name)
            if value and value.strip():
                non_sensitive_fields.append(field_id)

        descriptor = {
            "id": "composio",
            "kind": "composio",
            "display_name": "Composio",
            "help_text": "API key + connector config Hermes uses to talk to Composio integrations. Stored in macOS Keychain on this Mac; never synced to iCloud.",
            "test_action_available": True,
            "fields": [
                {"id": "api_key", "kind": "api_key", "label": "API key", "placeholder": "comp_live_…", "help_text": "Found in your Composio dashboard. Required.", "is_required": True},
                {"id": "base_url", "kind": "plain_text", "label": "Base URL", "placeholder": "https://backend.composio.dev", "help_text": "Override only if you self-host Composio.", "is_required": False},
                {"id": "entity_id", "kind": "plain_text", "label": "Entity ID", "placeholder": "default", "help_text": "Composio account/entity scoping. Optional.", "is_required": False},
                {"id": "redirect_url", "kind": "plain_text", "label": "Redirect URL", "placeholder": "diak://composio/callback", "help_text": "Where the daemon should send users after OAuth.", "is_required": False},
                {"id": "setup_url_template", "kind": "plain_text", "label": "Setup URL template", "placeholder": "https://composio.dev/connect/{connector}", "help_text": "Template used when the daemon hands off connector setup.", "is_required": False},
            ],
        }
        status = {
            "id": "composio",
            "presence": "saved" if api_key_present else "missing",
            "validity": "untested",
            "saved_non_sensitive_field_ids": non_sensitive_fields,
        }
        return {
            "descriptors": [descriptor],
            "statuses": [status],
            "boundary_note": "Diak stores API keys and integration config in macOS Keychain on this Mac. Hermes Engine reads them from Keychain at bridge launch — they are never written to plain config files or synced to iCloud.",
        }

    def _version_payload(self) -> dict[str, Any]:
        provider = None
        model = None
        try:
            if isinstance(self.server.runtime, HermesAgentRuntime):
                from gateway.run import _resolve_gateway_model, _resolve_runtime_agent_kwargs
                provider = _resolve_runtime_agent_kwargs().get("provider")
                model = _resolve_gateway_model()
            else:
                provider = getattr(self.server.runtime, "provider", None)
                model = getattr(self.server.runtime, "model", None)
        except Exception:
            pass
        return {
            "version": BRIDGE_VERSION,
            "build": "local",
            "profile": "production",
            "mode": "production_bridge",
            "runtime": "hermes-agent",
            "provider": provider,
            "model": model,
        }

    def _handle_get_session_path(self, path: str) -> None:
        stream_match = re.fullmatch(r"/sessions/([^/]+)/stream", path)
        if stream_match:
            return self._send_stream(stream_match.group(1))
        messages_match = re.fullmatch(r"/sessions/([^/]+)/messages", path)
        if messages_match:
            session_id = messages_match.group(1)
            if not self.server.state.get_session(session_id):
                return self._send_error(404, "Session not found")
            return self._send_json(200, self.server.state.get_messages(session_id))
        artifacts_match = re.fullmatch(r"/sessions/([^/]+)/canvas/artifacts", path)
        if artifacts_match:
            session_id = artifacts_match.group(1)
            if not self.server.state.get_session(session_id):
                return self._send_error(404, "Session not found")
            return self._send_json(200, {
                "session_id": session_id,
                "boundary_note": "Production bridge: artifacts are captured from real Hermes Agent runtime output; execution remains in Hermes Agent.",
                "artifacts": self.server.state.get_artifacts(session_id),
            })
        evidence_match = re.fullmatch(r"/sessions/([^/]+)/evidence", path)
        if evidence_match:
            session_id = evidence_match.group(1)
            if not self.server.state.get_session(session_id):
                return self._send_error(404, "Session not found")
            return self._send_json(200, self._list_evidence(session_id=session_id))
        session_match = re.fullmatch(r"/sessions/([^/]+)", path)
        if session_match:
            session = self.server.state.get_session(session_match.group(1))
            if not session:
                return self._send_error(404, "Session not found")
            return self._send_json(200, session)
        return self._send_error(404, "Not found")

    def _create_session(self, body: dict[str, Any]) -> None:
        prompt = str(body.get("prompt") or "").strip()
        if not prompt:
            return self._send_error(400, "Missing prompt")
        session_id = make_id("sess-diak")
        session = self._initial_session(session_id, prompt, project_id=body.get("project_id"))
        self.server.state.upsert_session(session)
        self.server.state.append_message(session_id, self._message(session_id, "user", prompt))
        return self._run_and_store(session_id, prompt, history=[])

    def _continue_session(self, session_id: str, body: dict[str, Any]) -> None:
        session = self.server.state.get_session(session_id)
        if not session:
            return self._send_error(404, "Session not found")
        prompt = str(body.get("prompt") or "").strip()
        if not prompt:
            return self._send_error(400, "Missing prompt")
        prior_messages = self.server.state.get_messages(session_id)
        history = [{"role": m["role"], "content": m.get("content", "")} for m in prior_messages if m.get("role") in ("user", "assistant")]
        self.server.state.append_message(session_id, self._message(session_id, "user", prompt))
        return self._run_and_store(session_id, prompt, history=history, preferred_session_id=session.get("hermes_session_id"))

    def _initial_session(self, session_id: str, prompt: str, *, project_id: Any = None) -> dict[str, Any]:
        now = utc_now()
        project = {"id": str(project_id), "name": str(project_id)} if project_id else None
        return {
            "id": session_id,
            "title": title_from_prompt(prompt),
            "summary": None,
            "status": "running",
            "created_at": now,
            "updated_at": now,
            "model": None,
            "project": project,
            "has_artifacts": False,
            "pending_approvals": 0,
            "hermes_session_id": None,
            "provider": None,
        }

    def _message(self, session_id: str, role: str, content: str, *, message_id: str | None = None, streaming: bool = False) -> dict[str, Any]:
        return {
            "id": message_id or make_id("msg"),
            "session_id": session_id,
            "role": role,
            "content": content,
            "created_at": utc_now(),
            "is_streaming": streaming,
            "tool_activities": [],
        }

    def _run_and_store(self, session_id: str, prompt: str, *, history: list[dict[str, str]], preferred_session_id: str | None = None) -> None:
        assistant_message_id = make_id("msg")
        events: list[dict[str, Any]] = [{"type": "message_started", "message_id": assistant_message_id, "session_id": session_id, "role": "assistant"}]
        deltas: list[str] = []

        def on_delta(delta: str | None) -> None:
            if not delta:
                return
            text = str(delta)
            deltas.append(text)
            events.append({"type": "message_delta", "message_id": assistant_message_id, "text_delta": text})

        session = self.server.state.get_session(session_id) or self._initial_session(session_id, prompt)
        try:
            result = self.server.runtime.run(prompt, history=history, preferred_session_id=preferred_session_id, stream_callback=on_delta)
            text = result.text
            # Some providers/configurations may not stream; synthesize one honest
            # delta from the final text so Diak still receives the canonical
            # envelope while preserving the real response content.
            if not deltas and text:
                events.append({"type": "message_delta", "message_id": assistant_message_id, "text_delta": text})
            assistant_message = self._message(session_id, "assistant", text, message_id=assistant_message_id)
            self.server.state.append_message(session_id, assistant_message)
            artifacts: list[dict[str, Any]] = []
            artifact = artifact_from_response(session_id, prompt, text)
            if artifact:
                artifacts = [artifact]
                self.server.state.set_artifacts(session_id, artifacts)
                events.append({"type": "canvas_updated", "session_id": session_id, "update": {"type": "select_tab", "tab": "browser"}})
            events.append({"type": "message_completed", "message_id": assistant_message_id, "content": text})
            events.append({"type": "session_ended", "session_id": session_id, "status": "completed"})
            session.update({
                "status": "completed",
                "summary": text[:240],
                "updated_at": utc_now(),
                "model": result.model,
                "provider": result.provider,
                "hermes_session_id": result.hermes_session_id,
                "has_artifacts": bool(artifacts),
            })
            self.server.state.upsert_session(session)
            self.server.state.set_events(session_id, events)
            return self._send_json(200, session, headers={"X-Hermes-Session-Id": result.hermes_session_id or ""})
        except Exception as exc:
            events.append({"type": "session_ended", "session_id": session_id, "status": "failed"})
            session.update({"status": "failed", "summary": str(exc)[:240], "updated_at": utc_now()})
            self.server.state.upsert_session(session)
            self.server.state.set_events(session_id, events)
            return self._send_error(502, "Hermes runtime failed", details=str(exc))

    def _send_stream(self, session_id: str) -> None:
        if not self.server.state.get_session(session_id):
            return self._send_error(404, "Session not found")
        events = self.server.state.get_events(session_id)
        self.send_response(200)
        self.send_header("Content-Type", "text/event-stream; charset=utf-8")
        self.send_header("Cache-Control", "no-cache")
        self.send_header("Connection", "close")
        self.end_headers()
        for event in events:
            payload = json_dumps(event).encode("utf-8")
            self.wfile.write(b"data: ")
            self.wfile.write(payload)
            self.wfile.write(b"\n\n")
            self.wfile.flush()


def build_server(config: BridgeConfig) -> DiakHermesBridgeServer:
    state = BridgeState(config.state_path, persist=config.persist_state)
    runtime = HermesAgentRuntime(config)
    return DiakHermesBridgeServer((config.bind_host, config.port), runtime=runtime, state=state, config=config)


def parse_args(argv: Iterable[str] | None = None) -> BridgeConfig:
    parser = argparse.ArgumentParser(description="Run the production Diak ↔ Hermes Agent bridge")
    parser.add_argument("--host", default=os.getenv("DIAK_BRIDGE_HOST", DEFAULT_HOST))
    parser.add_argument("--port", type=int, default=int(os.getenv("DIAK_BRIDGE_PORT", str(DEFAULT_PORT))))
    parser.add_argument("--state", default=os.getenv("DIAK_BRIDGE_STATE", str(DEFAULT_STATE_PATH)))
    parser.add_argument("--no-persist", action="store_true", default=os.getenv("DIAK_BRIDGE_NO_PERSIST") in ("1", "true", "yes"))
    parser.add_argument("--token", default=os.getenv("DIAK_BRIDGE_TOKEN") or None)
    parser.add_argument("--hermes-agent-path", default=os.getenv("HERMES_AGENT_PATH", str(Path.home() / ".hermes" / "hermes-agent")))
    parser.add_argument("--max-iterations", type=int, default=int(os.getenv("DIAK_BRIDGE_MAX_ITERATIONS", "90")))
    parser.add_argument("--composio-api-key", default=os.getenv("COMPOSIO_API_KEY") or None)
    parser.add_argument("--composio-api-base-url", default=os.getenv("COMPOSIO_API_BASE_URL", "https://backend.composio.dev/api/v1"))
    parser.add_argument("--connector-entity-id", default=os.getenv("DIAK_CONNECTOR_ENTITY_ID", "diak-local-user"))
    parser.add_argument("--connector-redirect-url", default=os.getenv("DIAK_CONNECTOR_REDIRECT_URL") or None)
    args = parser.parse_args(list(argv) if argv is not None else None)
    if args.host not in ("127.0.0.1", "localhost", "::1") and not args.token:
        parser.error("Non-local bind requires DIAK_BRIDGE_TOKEN/--token")
    return BridgeConfig(
        bind_host=args.host,
        port=args.port,
        state_path=Path(args.state).expanduser(),
        persist_state=not args.no_persist,
        token=args.token,
        hermes_agent_path=Path(args.hermes_agent_path).expanduser(),
        max_iterations=args.max_iterations,
        composio_api_key=args.composio_api_key,
        composio_api_base_url=args.composio_api_base_url,
        connector_entity_id=args.connector_entity_id,
        connector_redirect_url=args.connector_redirect_url,
    )


def main(argv: Iterable[str] | None = None) -> int:
    config = parse_args(argv)
    server = build_server(config)
    host, port = server.server_address[:2]
    print(f"Diak production Hermes bridge listening on http://{host}:{port}", flush=True)
    print(f"state={config.state_path} mode=production_bridge runtime=hermes-agent", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopping Diak production Hermes bridge", flush=True)
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
